# Perfecto Configuration - Public App Test 
perfecto.cloud.name=trial 
perfecto.security.token=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI2ZDM2NmJiNS01NDAyLTQ4MmMtYTVhOC1kODZhODk4MDYyZjIifQ.eyJpYXQiOjE3NjIyNjc3MTQsImp0aSI6Ijc1MjQ4YTcwLTdmYWQtNDM0NS1iODMxLTRmMmMwMDJjNmE1NCIsImlzcyI6Imh0dHBzOi8vYXV0aDMucGVyZmVjdG9tb2JpbGUuY29tL2F1dGgvcmVhbG1zL3RyaWFsLXBlcmZlY3RvbW9iaWxlLWNvbSIsImF1ZCI6Imh0dHBzOi8vYXV0aDMucGVyZmVjdG9tb2JpbGUuY29tL2F1dGgvcmVhbG1zL3RyaWFsLXBlcmZlY3RvbW9iaWxlLWNvbSIsInN1YiI6ImZiOTA1YmU1LWU4YzEtNDdiNS1iNjBiLTA1M2Y3OGI1ZjdjMSIsInR5cCI6Ik9mZmxpbmUiLCJhenAiOiJvZmZsaW5lLXRva2VuLWdlbmVyYXRvciIsIm5vbmNlIjoiZGEyZTQ0YTktN2Y5Zi00MjRkLTkzOGItYmFmZTUxNGYyZWI5Iiwic2Vzc2lvbl9zdGF0ZSI6IjlmNzI0ZDI2LTI5Y2YtNGI0Ny1iNmI1LTI4MjU0NWQxMjkxOCIsInNjb3BlIjoib3BlbmlkIG9mZmxpbmVfYWNjZXNzIHByb2ZpbGUgZW1haWwiLCJzaWQiOiI5ZjcyNGQyNi0yOWNmLTRiNDctYjZiNS0yODI1NDVkMTI5MTgifQ.R92QxTp0yE9behMuD42dh_wAf6RCMsR6aiztuJJgH40 
perfecto.url=https://${perfecto.cloud.name}.perfectomobile.com/nexperience/perfectomobile/wd/hub 
perfecto.project=Public App Test 
perfecto.build=Test_1.0 
perfecto.debug=true 
perfecto.video=true 
perfecto.network.logs=true 
perfecto.android.device.model=.* 
perfecto.android.os.version=.* 
perfecto.android.app.path=PUBLIC:ExpenseTracker/Native/ExpenseAppVer1.0.apk 
perfecto.android.app.package=io.perfecto.expense.tracker 
perfecto.ios.device.model=iPhone.* 
perfecto.ios.os.version=16 
perfecto.ios.app.path=PUBLIC:ExpenseTracker/Native/InvoiceApp1.0.ipa 
perfecto.ios.bundle.id=io.perfecto.expense.tracker 
perfecto.new.command.timeout=300 
perfecto.implicit.wait=10 
